# Generated by Django 4.0.4 on 2022-06-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('salary', models.FloatField()),
                ('phone', models.IntegerField()),
                ('role', models.CharField(max_length=30)),
                ('hiredate', models.IntegerField()),
                ('location', models.CharField(default=None, max_length=20, null=True)),
            ],
        ),
    ]
