# Generated by Django 4.0.4 on 2022-06-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hiredate',
            field=models.DateField(),
        ),
    ]
